version: '3.8'
services:
 db:
   image: mysql:5.7
   ports:
    - '3306:3306'
   container_name: 'hacker-boni'
   environment:
    MYSQL_ROOT_PASSWORD: 'boni2001'
    MYSQL_DATABASE: 'shreya'

 pyboni:
  image: moon
  build: .
  container_name: 'pagal'
  ports:
   - '8080:8000'
  command: python manage.py runserver 0.0.0.0:8000
  depends_on:
   - db

